# pylint: skip-file

import datetime

import pytest

from wednesday import get_villain_name

format_str = '%d/%m/%Y'  # The format


def test_get_villain_name_with_known_dates_evil_pickle():
    assert get_villain_name(datetime.datetime.strptime(
        "1/1/2000", format_str)) == "The Evil Pickle"


def test_get_villain_name_with_known_dates_vile_hood():
    assert get_villain_name(datetime.datetime.strptime(
        "2/2/2000", format_str)) == "The Vile Hood Ornament"


def test_get_villain_name_with_known_dates_awkward_good():
    assert get_villain_name(datetime.datetime.strptime(
        "2/12/2000", format_str)) == "The Awkward Hood Ornament"


@pytest.mark.parametrize("birthdate,name",
                         [(datetime.datetime(2180, 11, 22, 21, 37, 14), "The Terrifying Hood Ornament"),
                          (datetime.datetime(2030, 10, 22, 21, 55, 24),
                           "The Orange Hood Ornament"),
                             (datetime.datetime(2033, 4, 28, 17, 42, 11),
                              "The Trashy Teaspoon"),
                             (datetime.datetime(2046, 6, 22, 23, 53, 32),
                              "The Embarrassing Hood Ornament"),
                             (datetime.datetime(2014, 5, 5, 13, 47, 33),
                              "The Despicable Potato"),
                             (datetime.datetime(2037, 12, 21, 21, 20, 14),
                              "The Awkward Pickle"),
                             (datetime.datetime(2092, 5, 21, 22, 12, 58),
                              "The Despicable Pickle"),
                             (datetime.datetime(1975, 12, 22, 5, 4, 45),
                              "The Awkward Hood Ornament"),
                             (datetime.datetime(2239, 6, 30, 7, 5, 56),
                              "The Embarrassing Mustache"),
                             (datetime.datetime(2248, 9, 26, 20, 42, 15),
                              "The Twirling Tomato"),
                             (datetime.datetime(2150, 4, 15, 19, 16, 10),
                              "The Trashy Potato"),
                             (datetime.datetime(2203, 5, 6, 13, 2, 33),
                              "The Despicable Tomato"),
                             (datetime.datetime(2036, 7, 6, 17, 57, 38),
                              "The Disreputable Tomato"),
                             (datetime.datetime(2135, 4, 26, 8, 32, 46),
                              "The Trashy Tomato"),
                             (datetime.datetime(2242, 9, 12, 23, 42, 32),
                              "The Twirling Hood Ornament"),
                             (datetime.datetime(2186, 3, 23,
                              14, 53, 20), "The Cruel Raisin"),
                             (datetime.datetime(2010, 2, 22, 23, 32, 12),
                              "The Vile Hood Ornament"),
                             (datetime.datetime(2061, 1, 16,
                              4, 26, 9), "The Evil Tomato"),
                             (datetime.datetime(2201, 10, 6, 19, 19, 31),
                              "The Orange Tomato"),
                             (datetime.datetime(2152, 7, 20, 12, 17, 54),
                              "The Disreputable Mustache"),
                             (datetime.datetime(2271, 10, 6, 20, 33, 21),
                              "The Orange Tomato"),
                             (datetime.datetime(2033, 7, 27, 6, 17, 15),
                              "The Disreputable House Cat"),
                             (datetime.datetime(2044, 12, 31, 1, 19, 54),
                              "The Awkward Pickle"),
                             (datetime.datetime(2211, 12, 5, 17, 39, 25),
                              "The Awkward Potato"),
                             (datetime.datetime(2050, 2, 10, 2, 13, 58),
                              "The Vile Mustache"),
                             (datetime.datetime(2159, 9, 9, 23, 36, 5),
                              "The Twirling Laundry Basket"),
                             (datetime.datetime(2055, 12, 9, 19, 54, 9),
                              "The Awkward Laundry Basket"),
                             (datetime.datetime(2170, 6, 6, 22, 55, 10),
                              "The Embarrassing Tomato"),
                             (datetime.datetime(2181, 11, 1, 13, 48, 14),
                              "The Terrifying Pickle"),
                             (datetime.datetime(2074, 12, 18, 6, 30, 7),
                              "The Awkward Teaspoon"),
                             (datetime.datetime(2241, 6, 9, 9, 46, 51),
                              "The Embarrassing Laundry Basket"),
                             (datetime.datetime(2120, 11, 24, 0, 6, 6),
                              "The Terrifying Recycling Bin"),
                             (datetime.datetime(2286, 10, 13,
                              12, 16, 34), "The Orange Raisin"),
                             (datetime.datetime(2263, 4, 18, 9, 20, 46),
                              "The Trashy Teaspoon"),
                             (datetime.datetime(2086, 10, 28, 8, 7, 59),
                              "The Orange Teaspoon"),
                             (datetime.datetime(2038, 9, 27, 4, 0, 6),
                              "The Twirling House Cat"),
                             (datetime.datetime(2001, 10, 21,
                              15, 43, 22), "The Orange Pickle"),
                             (datetime.datetime(2112, 5, 2, 1, 3, 43),
                              "The Despicable Hood Ornament"),
                             (datetime.datetime(2149, 3, 17, 7, 6, 8),
                              "The Cruel House Cat"),
                             (datetime.datetime(2264, 9, 23, 5, 37, 1),
                              "The Twirling Raisin"),
                             (datetime.datetime(2070, 6, 23, 18, 22, 28),
                              "The Embarrassing Raisin"),
                             (datetime.datetime(1999, 5, 10, 7, 13, 10),
                              "The Despicable Mustache"),
                             (datetime.datetime(2249, 1, 21,
                              0, 15, 26), "The Evil Pickle"),
                             (datetime.datetime(2098, 8, 5, 0, 4, 57),
                              "The Atrocious Potato"),
                             (datetime.datetime(2056, 1, 2, 4, 50, 54),
                              "The Evil Hood Ornament"),
                             (datetime.datetime(2131, 8, 8, 5, 56, 51),
                              "The Atrocious Teaspoon"),
                             (datetime.datetime(2140, 4, 15, 14, 36, 42),
                              "The Trashy Potato"),
                             (datetime.datetime(2073, 1, 12, 14, 39, 46),
                              "The Evil Hood Ornament"),
                             (datetime.datetime(1991, 8, 4, 19, 58, 10),
                              "The Atrocious Recycling Bin"),
                             (datetime.datetime(2028, 12, 28, 10, 4, 34),
                              "The Awkward Teaspoon"),
                             (datetime.datetime(2097, 4, 20, 2, 28, 1),
                              "The Trashy Mustache"),
                             (datetime.datetime(2278, 5, 1, 18, 57, 20),
                              "The Despicable Pickle"),
                             (datetime.datetime(2280, 4, 28, 23, 52, 40),
                              "The Trashy Teaspoon"),
                             (datetime.datetime(2105, 1, 14, 7, 31, 8),
                              "The Evil Recycling Bin"),
                             (datetime.datetime(2096, 1, 26, 6, 15),
                              "The Evil Tomato"),
                             (datetime.datetime(2235, 5, 13, 6, 44, 46),
                              "The Despicable Raisin"),
                             (datetime.datetime(2207, 8, 16, 1, 36, 50),
                              "The Atrocious Tomato"),
                             (datetime.datetime(2070, 12, 23, 22, 18, 30),
                              "The Awkward Raisin"),
                             (datetime.datetime(2072, 4, 5, 15, 18, 18),
                              "The Trashy Potato"),
                             (datetime.datetime(2077, 7, 5, 8, 58, 30),
                              "The Disreputable Potato"),
                             (datetime.datetime(2116, 4, 24, 9, 37, 46),
                              "The Trashy Recycling Bin"),
                             (datetime.datetime(2259, 2, 18, 11, 34, 57),
                              "The Vile Teaspoon"),
                             (datetime.datetime(2017, 2, 2, 1, 7, 27),
                              "The Vile Hood Ornament"),
                             (datetime.datetime(2003, 12, 8, 9, 58, 42),
                              "The Awkward Teaspoon"),
                             (datetime.datetime(2124, 3, 30, 10, 31, 34),
                              "The Cruel Mustache"),
                             (datetime.datetime(1996, 8, 27, 21, 13, 27),
                              "The Atrocious House Cat"),
                             (datetime.datetime(2087, 1, 2, 0, 9, 48),
                              "The Evil Hood Ornament"),
                             (datetime.datetime(2236, 3, 15,
                              4, 47, 4), "The Cruel Potato"),
                             (datetime.datetime(2017, 9, 18, 21, 41, 8),
                              "The Twirling Teaspoon"),
                             (datetime.datetime(2265, 8, 26, 13, 42, 12),
                              "The Atrocious Tomato"),
                             (datetime.datetime(2094, 5, 17, 20, 43, 22),
                              "The Despicable House Cat"),
                             (datetime.datetime(2187, 6, 3, 17, 51, 47),
                              "The Embarrassing Raisin"),
                             (datetime.datetime(2203, 6, 11, 16, 55, 57),
                              "The Embarrassing Pickle"),
                             (datetime.datetime(2076, 7, 3, 4, 20, 32),
                              "The Disreputable Raisin"),
                             (datetime.datetime(2050, 10, 25,
                              5, 47, 44), "The Orange Potato"),
                             (datetime.datetime(2002, 7, 8, 8, 2, 48),
                              "The Disreputable Teaspoon"),
                             (datetime.datetime(2006, 3, 31,
                              17, 35, 42), "The Cruel Pickle"),
                             (datetime.datetime(2046, 1, 16,
                              5, 35, 46), "The Evil Tomato"),
                             (datetime.datetime(2231, 12, 11, 1, 14, 58),
                              "The Awkward Pickle"),
                             (datetime.datetime(2253, 2, 18, 3, 52, 23),
                              "The Vile Teaspoon"),
                             (datetime.datetime(2059, 10, 31,
                              6, 27, 16), "The Orange Pickle"),
                             (datetime.datetime(2054, 5, 27, 14, 44, 47),
                              "The Despicable House Cat"),
                             (datetime.datetime(2198, 3, 16,
                              11, 46, 29), "The Cruel Tomato"),
                             (datetime.datetime(2130, 8, 12, 10, 59, 21),
                              "The Atrocious Hood Ornament"),
                             (datetime.datetime(1988, 6, 6, 2, 8, 38),
                              "The Embarrassing Tomato"),
                             (datetime.datetime(2235, 6, 16, 4, 6, 19),
                              "The Embarrassing Tomato"),
                             (datetime.datetime(2210, 6, 14, 2, 47, 29),
                              "The Embarrassing Recycling Bin"),
                             (datetime.datetime(2113, 8, 16, 8, 33, 15),
                              "The Atrocious Tomato"),
                             (datetime.datetime(2106, 10, 9, 1, 5, 59),
                              "The Orange Laundry Basket"),
                             (datetime.datetime(2138, 11, 23, 5, 12, 4),
                              "The Terrifying Raisin"),
                             (datetime.datetime(2152, 12, 21, 13, 21, 5),
                              "The Awkward Pickle"),
                             (datetime.datetime(2152, 1, 25,
                              14, 41, 59), "The Evil Potato"),
                             (datetime.datetime(2218, 12, 13, 23, 45, 44),
                              "The Awkward Raisin"),
                             (datetime.datetime(2092, 7, 12, 15, 7, 29),
                              "The Disreputable Hood Ornament"),
                             (datetime.datetime(2087, 2, 19, 0, 30, 1),
                              "The Vile Laundry Basket"),
                             (datetime.datetime(1993, 9, 24, 14, 36, 48),
                              "The Twirling Recycling Bin"),
                             (datetime.datetime(2249, 7, 2, 21, 18, 32),
                              "The Disreputable Hood Ornament"),
                             (datetime.datetime(2059, 4, 13, 18, 4, 19),
                              "The Trashy Raisin"),
                             (datetime.datetime(2090, 9, 28, 3, 53, 59),
                              "The Twirling Teaspoon"),
                             (datetime.datetime(2225, 9, 10, 5, 37, 2), "The Twirling Mustache")])
def test_random_test_cases(birthdate, name):
    assert get_villain_name(birthdate) == name
